try:
    print(a)
except Exception as ex:
    print(ex)

